### ISSUE TITLE
Missing cstring include in udpdatacontroller.cpp

### ISSUE THREAD

**Issue by lrowen** [f4exb/serialDV#6]
On CentOS 7, build errors with following (several times):
[lowen@dhcp-pool101 build]$ make
[ 14%] Building CXX object CMakeFiles/serialdv.dir/udpdatacontroller.cpp.o
/home/lowen/development/sdr-stuff/serialDV/udpdatacontroller.cpp: In member function ‘void SerialDV::UDPDataController::openSocket(int)’:
/home/lowen/development/sdr-stuff/serialDV/udpdatacontroller.cpp:155:105: error: ‘strerror’ was not declared in this scope
         std::cerr << "UDPDataController::openSocket: error when creating the socket: " << strerror(errno) << std::endl;

Adding a #include &lt;cstring&gt; 
fixes this build error.

**Comment by f4exb** [comment]
Updated your comment because the markdown processor takes lower than and greater than signs as delimiters.

**Comment by lrowen** [comment]
Build on CentOS 7 now works fine.  Thanks!
