### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by nicoonoclaste** [f4exb/serialDV#8]
While packaging sdrangel (and its dependencies) for Debian, I discovered this library doesn't seem to specify a license, which technically means we cannot redistribute it, in source or binary form (people need explicit permission for that)

Please consider specifying a license.

**Comment by nicoonoclaste** [comment]
PS: Some (all?) the files specify the GPLv3 in a header, but making the situation clearer would still be appreciated.

**Comment by f4exb** [comment]
Fixed in v1.1.2
